### ISSUE TITLE
After installing the Jenkins on ubuntu not able to access it through the url

### ISSUE THREAD

**Issue by naresh86** [QT-DevOps/DevOpsIssues#958] opened 2020-09-25 11:09 UTC
Hi Sir,

I have created the ubuntu instance and installed the Jenkin using the specified commands and it got installed successfully but I am unable to access it from the url (<IP Address>:8080), getting the below issue. I created multiple machines and verified getting the same issue.

Please help me to resolve this issue

![image](https://user-images.githubusercontent.com/8927418/94260176-51e8d700-ff4d-11ea-81e1-c7f1fedc03d7.png)

**Comment by naresh86** [comment] 2020-09-25 11:32
Hi Sir,

I have fixed the above issue by adding a new security group rule as shown below

![image](https://user-images.githubusercontent.com/8927418/94262212-beb1a080-ff50-11ea-92b0-74d8d3a9a9a1.png)

After above setting  I am able to access the url.

![image](https://user-images.githubusercontent.com/8927418/94262317-eacd2180-ff50-11ea-8cd0-b076cd79982e.png)


Thank you sir..

Regards
Naresh

**Comment by badaltechiepi** [comment] 2020-09-26 12:54
@naresh86 Please close the issue if the issue is fixed.

**Closed as completed** 2020-09-28 14:48 UTC
